### ISSUE TITLE
Every installation is tracked as organic

### ISSUE THREAD

**Issue by eabuslaiman30** [AppsFlyerSDK/react-native-appsflyer#73]
We're trying to implement the collection of the installs by Facebook. Anyway, seems that all they are being count as **Organic installations.**

We read this article As this guide says https://support.appsflyer.com/hc/en-us/articles/207033826-Facebook-Ads-Setup-Guide#Integration which says this: "Your app MUST collect IDFA or GAID or all your Facebook installs are attributed as organic. For further information refer to the SDK Integrations Guides for either iOS or Android."

Anyway, you don't have any information in your readme about this.

How can we count the facebook installs? Any solution?

Thanks,

**Comment by dmitriiivashko** [comment]
Having the same issue. All Facebook Android installs are tracked as organic

**Comment by antseburova** [comment]
Did anybody find a solution for this?

**Comment by af-vs** [comment]
Hello, everyone!

1. If you see an organic response in the onInstallConversionData callback, it can be caused by Facebook Privacy Policy. In order to be able to access user-level data, please make sure to sign Facebook ToS - https://support.appsflyer.com/hc/en-us/articles/207033826-Facebook-Ads-setup-guide#integration-userlevel-data

2. If you see installs as organic in the raw data or in the Dashboard and you believe that these specific installs should have been attributed to the Facebook media source, please open a ticket to our Support Team (at support@appsflyer.com. Please make sure to specify your AppsFlyer account email address and app ID) and we will be happy to investigate this matter for you. Facebook (and other media sources) installs may not be attributed properly due to multiple reasons unique per customer/app configuration and it is not necessarily related to SDK.

Thank you!
